export REACT_APP_ACCESS_NODE=${ACCESS_API}
export REACT_APP_WALLET_DISCOVERY=${WALLET_DISCOVERY}
export REACT_APP_FT_CONTRACT=${FT_CONTRACT}
export REACT_APP_FUSD_CONTRACT=${FUSD_CONTRACT}
export REACT_APP_DAPPY_CONTRACT=${DAPPY_CONTRACT}

npm run start